# This program computes the integrated Keff of a Boolean network.

# Basic idea:
# The original measure of effective connectivity (Keff) is extended to a temporally integrated Boolean network, resulting 
# in the measure of 'integrated Keff'. This is simply the time-indexed Keff of the nodes of a Boolean network, where the
# time index refers to a time step of the integration procedure. For more details on the integration method itself, please
# see comments in 'ComputeIntegrateBoolNet.R'.

# Input:
# A 'schema causation chain' generated by the 'IntegrateBoolNet' procedure for a Boolean network.

# Output:
# A 'Keff timeseries' matrix whose rows indicate time, columns indicate the variables or nodes of the Boolean network, 
# and the values in the cells indicate the Keff of the corresponding node at the corresponding time. This matrix contains 
# at least one row and at least one column, provided that the Boolean network consists of at least one node.

# USAGE EXAMPLE:
# require(BoolNet)
# Net <- loadNetwork("./Data/ExampleBooleanNetwork.bn", symbolic = F)
# SchemaCausationChain = IntegrateBoolNet(Net, NumIters = 5)
# IntegratedKeff = ComputeIntegratedKeff(SchemaCausationChain)
# print(IntegratedKeff)

ComputeIntegratedKeff <- function(SchemaTransitionChain) {
  
  N = length(SchemaTransitionChain)
  
  Keff_TimeSeries = c()

  MaxStepsNodeWise = sapply(SchemaTransitionChain, function(s) length(s))
  MaxNumSteps = max(MaxStepsNodeWise)
  
  for (t in 1 : MaxNumSteps) {
    
    KeffNodeWiset = c()
    
    for (n in 1 : N) {   
      
      MaxIters = length(SchemaTransitionChain[[n]])  # MaxIters may vary depending on n, but is a minimum of 1
      
      if (t <= MaxIters) {
        
        Sch0 = SchemaTransitionChain[[n]][[t]][[1]]
        Sch1 = SchemaTransitionChain[[n]][[t]][[2]]
        
        SchemataSet = list()
        SchemataSet[[1]] = Sch0
        SchemataSet[[2]] = Sch1
        
      }
      
      if (t > MaxIters) {
        
        Keff = Keff_TimeSeries[t - 1, n]
        
      } else {
        
        Keff = ComputeKeffFromSchemata(SchemataSet)  # NA will be handled there
        
      }
      
      KeffNodeWiset = c(KeffNodeWiset, Keff)
      
    }
    
    Keff_TimeSeries = rbind(Keff_TimeSeries, KeffNodeWiset)
    
  }
  
  Keff_TimeSeries = matrix(Keff_TimeSeries, ncol = ncol(Keff_TimeSeries))
  
  return(Keff_TimeSeries)
  
}
















